### ISSUE TITLE
elisp mode autocomplete problems

### ISSUE THREAD

**Issue by vv111y** [bmag/emacs-purpose#105]
I was recommended by spacemacs crowd to report here. When in elisp mode, company autocomplete minor-mode is enabled and would cause severe delays, making it unusable. I put this in my dotfile

  ```(purpose-mode -1)```

And that fixes the problem. now an autocomplete does show up, but it is very quick.

**Comment by bmag** [comment]
I'm not experiencing any delays here, but if you have the x-kill extension enabled, that may hurt performance (see #76). You can check if it's enabled by looking at the value of `purpose-mode-hook`: if the hook contains `purpose-x-kill-sync` the x-kill is enabled, otherwise it's disabled. You can disable it by calling `purpose-x-kill-unset`.

**Comment by vv111y** [comment]
Sorry, I didn't see the notification. It is set as
```Its value is (spacemacs/window-purpose-sync-popwin)```
