### ISSUE TITLE
[WISH] Integration with Coveralls, undercover.el, etc.

### ISSUE THREAD

**Issue by jinnovation** [bmag/emacs-purpose#49]
In #46, @bmag mentions [this post](http://sachachua.com/blog/2015/02/continuous-integration-code-coverage-emacs-packages-travis-coveralls/) as being the basis upon which `Makefile` was designed.

This same post outlines a procedure to integrate an Emacs package project with [Coveralls.io](coveralls.io), a code coverage tool.

I'd argue that integrating `emacs-purpose` with Coveralls would greatly benefit development efforts in the long run.

**Comment by bmag** [comment]
That's true. I've started doing this, but stopped in the middle. I'm planning to finish the process, but not sure when.
This is the current state of coveralls and emacs-purpose:
- coverage for emacs-snapshot mostly works
- coverage for emacs stable (24.3) doesn't work. For some reason, using undercover.el causes the tests to fail.
- there is no coverage for files window-purpose-x.el and window-purpose-fixes.el, since I did not write tests for them yet
- coveralls reports some lines as not covered, even though it seems that they do run

So there is some integration with coveralls.io, but I don't mention it in the README because the coverage results don't mean much, yet.

**Comment by jinnovation** [comment]
Fair enough. I mention this because, in implementing the completion interface for `set-window-purpose` in #48, I noticed that the `dont-dedicate` flag didn't seem to work properly even before my changes, which leads me to think that that functionality may be broken.

I may contribute a test for that at some point, but that's a job for another PR and another day.

**Comment by bmag** [comment]
Purpose now has full integration with Coveralls and is tested on versions 24.3, 24.4 and 24.5 of Emacs :smiley: 
Still missing some tests, but the framework is there.
