### ISSUE TITLE
Without-purpose for dired-mode 

### ISSUE THREAD

**Issue by aagaard** [bmag/emacs-purpose#62]
In dired it would be nice to open a file without purpose using C-u. A similar functionality is implemented for find-file.

**Comment by bmag** [comment]
You could implement it in your emacs configuration by running this code after loading dired:
```emacs-lisp
(defalias 'my-dired-find-file-without-purpose
  (without-purpose-command #'dired-find-file))

(define-purpose-prefix-overload my-dired-find-file-overload
  '(dired-find-file my-dired-find-file-without-purpose))

(define-key dired-mode-map (kbd "RET") #'my-dired-find-file-overload)
```
I am reluctant to include it in Purpose because it isn't clear how helpful it is to most people, if at all. I'd also rather not override keys unless necessary, so as not to surprise users or interfere with any customization they may already have in place.

However, I realize now that I should add to the project's documentation an explanation of how to do what you suggested.

**Comment by aagaard** [comment]
I think dired is quite a common mode for switching between files too, so I found it a bit odd it wasn't included. But I think adding it to the documentation is good enough. Thanks! :+1:

**Comment by bmag** [comment]
Updated the documentation:
https://github.com/bmag/emacs-purpose/wiki/Usage#imitate-purpose-find-file-overload
https://github.com/bmag/emacs-purpose/wiki/Usage#creating-custom-commands
