### ISSUE TITLE
purpose-mode vs display-buffer-alist

### ISSUE THREAD

**Issue by malb** [bmag/emacs-purpose#81]
I have

```emacs-lisp
(defvar malb/popup-windows '("\\`\\*helm flycheck\\*\\'"
                             "\\`\\*Help\\*\\'"))

(dolist (name malb/popup-windows)
  (add-to-list 'display-buffer-alist
               `(,name
                 (display-buffer-reuse-window
                  display-buffer-in-side-window)
                 (reusable-frames . visible)
                 (side            . bottom)
                 (window-height   . 0.3))))
```

in my `init.el`. Now, if I enable `purpose-mode` then this configuration is ignored. Is that intentional?

**Comment by bmag** [comment]
Yes, this is intentional. Purpose works by setting `display-buffer-overriding-action`, which has a higher priority than `display-buffer-alist`.

You can make Purpose ignore certain buffers, thus letting the original `display-buffer` display those buffers according to `display-buffer-alist`. You do it by adding suitable regexps to the list of regexps `purpose-action-function-ignore-buffer-names`. By default, that list already contains entries for all Helm buffers, so `*helm flycheck*` is already covered.
In your case, you can change your code as follows:
```elisp
(defvar malb/popup-windows '("\\`\\*helm flycheck\\*\\'"
                             "\\`\\*Help\\*\\'"))

(dolist (name malb/popup-windows)
  (add-to-list 'purpose-action-function-ignore-buffer-names name)
  (add-to-list 'display-buffer-alist
               `(,name
                 (display-buffer-reuse-window
                  display-buffer-in-side-window)
                 (reusable-frames . visible)
                 (side            . bottom)
                 (window-height   . 0.3))))
```

Alternatively, you can use `purpose-special-action-sequences`.

**Comment by malb** [comment]
Excellent, thanks for explaining.
