### ISSUE TITLE
helm-find-file is disabled when using purpose mode

### ISSUE THREAD

**Issue by tsdeng** [bmag/emacs-purpose#87]
Hi, I really love this package.
I was using helm-find-file and bind the function to C-x C-f using:
`(global-set-key` (kbd "C-x C-f")  'helm-find-files)`

After enabling the purpose mode, C-x C-f gets override to purpose-find-file-overload and the behavior seems to fallback to the oringinal find-file function..

How can I make helm and purpose-mode play well together?

Thanks you!

**Comment by bmag** [comment]
Purpose binds `C-x C-f` in `purpose-mode-map`, so you need to change that binding.
```elisp
(with-eval-after-load 'window-purpose
  ;; remove purpose-mode's C-x C-f binding
  (define-key purpose-mode-map (kbd "C-x C-f") nil))
```
You can do the same thing for `C-x b`.

**Comment by tsdeng** [comment]
Is there a reason why purpose-mode wanna override the find-file function?

**Comment by bmag** [comment]
Yes. `C-u C-x C-f` lets you open a file and ignore Purpose when choosing a window to display a file. Normally Purpose tries to keep your window layout as it is, so `C-u C-x C-f` is a way to change the window layout.

For example, lets say you have two windows open - one showing a source file and one showing  a terminal. The focus is on the terminal window, and you want to open a new source file. With `C-x C-f`, the file will be displayed in the existing source file window. But with `C-u C-x C-f`, the file will be displayed in the current window instead of the terminal. This way you can  change the layout from one source window and one terminal window to two source windows.

`C-u C-x b` exists for the same reason.
