### ISSUE TITLE
Does not properly remember size of sr-speedbar

### ISSUE THREAD

**Issue by samis** [bmag/emacs-purpose#88]
I want this package to also remember the presence of sr-speedbar and it's appropriate buffer. However, this does not work (either it's the wrong size or I just get a useless dummy buffer.) How can I properly integrate this package with sr-speedbar?

**Comment by bmag** [comment]
Thanks for the report. It's not clear what you are trying to do. Can you provide a step-by-step recipe to produce the problem, including the observed behaviour (what happens) and the expected behaviour (what you want to happen)?
If a pair of before/after screen-shots can be relevant, please include it as well.
If you have some personal purpose configuration, please include your purpose-related configuration as well.

I think you mean that if you have an open speedbar window and save the window layout with `purpose-save-window-layout`, then later in a new emacs session load the layout with `purpose-load-window-layout`, you don't get a speedbar window. The rest of my answer is based on this assumption.

When Purpose save a window layout, it saves the size, location and purpose of each window. It doesn't save the actual buffer. When Purpose loads a window layout, it creates windows with the same size, location, and purpose. Now, changing a window's purpose is done by changing its buffer to a buffer with the desired purpose. So when you load a layout, each window needs to display a buffer with the correct purpose. If there is no buffer that matches a window's purpose, then a dummy buffer is created and displayed in that window.

In your case, the dummy buffer can be created if you load the layout when the speedbar buffer doesn't exist, e.g. before first invoking `sr-speedbar` or if the speedbar buffer has been killed. However, if the dummy buffer exists, and you invoke `sr-speedbar`, then the speedbar should be displayed instead of the dummy buffer (assuming the two buffers have the same purpose).

As for the window having the wrong size, without more details I can't know why that happens.

**Comment by samis** [comment]
My configuration is available here: https://github.com/samis/dotfiles/tree/master/emacs/.emacs.d
Original Window layout: http://www.enlightenment.org/ss/e-56e0735cbafb79.04834923.png
After restarting emacs (I automatically load the 'coding' configuration on start as you can see in the above directory): http://www.enlightenment.org/ss/e-56e07516a25685.89141282.png

Note how the window containing the speedbar buffer has drastically increased. (The dummy buffers are working fine and as such are not a problem.)

**Comment by bmag** [comment]
The issue with the wrong sizes should be fixed by f00cbc038b900ff79ea64028b8d89562d3c7e334, and will be available from MELPA in a few hours. Is everything working properly now?

**Comment by bmag** [comment]
No answer for a week, so I assume the problem has been fixed.
